//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalCenterFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationCenterEntities : DbContext
    {
        public EducationCenterEntities()
            : base("name=EducationCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<enrollments> enrollments { get; set; }
        public virtual DbSet<exams> exams { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
