//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalCenterFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int QuestionId { get; set; }
        public string QuestionContent { get; set; }
        public string QuestionAnswer { get; set; }
        public bool IsAnswered { get; set; }
        public Nullable<System.DateTime> AnswerCreatedAt { get; set; }
        public System.DateTime QuestionCreatedAt { get; set; }
    }
}
