//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalCenterFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int questionId { get; set; }
        public string questionContent { get; set; }
        public string questionAnswer { get; set; }
        public Nullable<bool> isAnswered { get; set; }
    }
}
